docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - echo "sakib starts"
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY_IMAGE
    - echo $DOCKER_ACCESS_TOKEN
    - echo "sakib ends"
    - export DOCKER_AUTH_CONFIG="{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$DOCKER_ACCESS_TOKEN\"}}}"
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main


docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - export DOCKER_AUTH_CONFIG="{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$DOCKER_ACCESS_TOKEN\"}}}"
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - main
