build:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin
  script:
    - |
      for SERVICE in $SERVICES; do
        if [ -d "$SERVICE" ]; then
          echo "Building and pushing $SERVICE service..."
          VERSION=$(grep '<version>' $SERVICE/pom.xml | sed -n '2s/[^0-9.]//gp')
          docker build -t $DOCKERHUB_USER/test:$SERVICE-$VERSION ./$SERVICE/
          docker push $DOCKERHUB_USER/test:$SERVICE-$VERSION
        else
          echo "Directory $SERVICE not found. Skipping..."
        fi
      done
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - app/**
        - db/**
  variables:
    SERVICES: ["app", "db"]
