image: docker:dind  # Use the Docker-in-Docker executor

services:
  - docker:dind  # Define a Docker service for building within a container

stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t sakib75/react_ci_cd:latest .  # Replace with your actual image name and tag if needed
  only:
    - master  # Run this stage only on pushes to the master branch (adjust as needed)

push:
  stage: push
  script:
    - docker login "registry-1.docker.io" -u "sakib75" -p "dckr_pat_YUogwaZmsRWsusBWaXl_rT0So90"  # **WARNING: Not recommended for production!**
    - docker push sakib75/react_ci_cd:latest  # Replace with your actual image name and tag if needed
  only:
    - master
  artifacts:
    paths:
      - sakib75/react_ci_cd:latest  # Upload the built image as an artifact (optional)

cache:
  paths:
    - node_modules/  # Cache dependencies to speed up builds (adjust based on your project)
