image: node:18-alpine

stages:
  - build_and_push

build_and_push:
  stage: build_and_push
  script:
    - apk add --no-cache git 
    - echo $CI_JOB_TOKEN | docker login -u sakib75 --password-stdin  
    - docker build -t sakib75/react_ci_cd:latest .  
    - docker push sakib75/react_ci_cd:latest

variables:
  DOCKER_USERNAME: $DOCKER_USERNAME  # Protected variable in GitLab settings
