image: docker:latest

stages:
  - build_and_push

variables:
  DOCKER_IMAGE_NAME: "sakib75/react_ci_cd"

build_and_push:
  stage: build_and_push
  script:
    - apk add --no-cache git
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $DOCKER_IMAGE_NAME:latest .
    - docker push $DOCKER_IMAGE_NAME:latest
