image: node:18-alpine  # Image with Node.js for building React app

stages:
  - build_and_push  # Stage for building and pushing the image

build_and_push:
  stage: build_and_push
  script:
    - apk add --no-cache npm  # Install npm
    - cd app  # Change directory to the app directory
    - npm install  # Install dependencies
    - npm run build  # Build the React app (adjust if needed)
    - docker build -t sakib75/react_ci_cd:latest .  # Build Docker image (replace with your username)
  artifacts:
    paths:
      - app/build/  # Specify the output directory of your build process (adjust path if needed)
  only:
    - main  # Run the pipeline only for pushes to the master branch (optional)

variables:
  DOCKER_USERNAME: $DOCKER_USERNAME  # Protected variable in GitLab settings