image: node:18-alpine  # Image with Node.js for building React app

stages:
  - build_and_push  # Stage for building and pushing the image

variables:
  DOCKER_USERNAME: $DOCKER_USERNAME  # Protected variable in GitLab settings
  DOCKER_PASSWORD: $DOCKER_PASSWORD  # New protected variable for Docker registry password

build_and_push:
  stage: build_and_push
  script:
    - apk add --no-cache npm  # Install npm
    - npm install -g serve  # Install serve for serving the static files
    - npm install          # Install dependencies
    - npm run build        # Build the React app (adjust if needed)
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin  # Login to Docker registry
    - docker push sakib75/react_ci_cd:latest  # Push the image to your registry
  artifacts:
    paths:
      - app/build/  # Specify the output directory of your build process (adjust path if needed)