docker-build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "$CI_REGISTRY_USER"
    - echo "$CI_REGISTRY_ACCESS_TOKEN"
    - echo "$CI_REGISTRY"
    - echo "Logging into Docker registry..."
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_ACCESS_TOKEN" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main
