image: docker:dind

stages:
  - build_and_push

build_and_push:
  stage: build_and_push
  script:
    - apk add --no-cache git  # Install Git if needed on runner
  
    # Optional debug commands (uncomment if needed)
    # - docker --version
    # - docker info
    # - docker ps
  
    - docker build -t sakib75/react_ci_cd:latest .
    - docker push sakib75/react_ci_cd:latest

variables:
  DOCKER_USERNAME: $DOCKER_USERNAME  # Protected variable in GitLab settings
