image: docker:dind  # Use the Docker-in-Docker executor

services:
  - docker:dind  # Define a Docker service for building within a container

stages:
  - build and push 


build and push:
  stage: build and push
  script:
    - docker login -u "sakib75" -p "dckr_pat_YUogwaZmsRWsusBWaXl_rT0So90" "docker.io"
    - docker build -t sakib75/react_ci_cd:latest .
    - docker push sakib75/react_ci_cd:latest 
  only:
    - main
  artifacts:
    paths:
      - sakib75/react_ci_cd:latest  
cache:
  paths:
    - node_modules/   # Cache dependencies to speed up builds (adjust based on your project)
