image: docker:dind 

services:
  - docker:dind  

stages:
  - build and push 


build and push:
  stage: build and push
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_ACCESS_TOKEN "docker.io"
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest 
  only:
    - main
  artifacts:
    paths:
      - $CI_REGISTRY_IMAGE:latest  
cache:
  paths:
    - node_modules/  
