docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "Logging into Docker registry..."
    - winpty docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PAT" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - main

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "Logging into Docker registry..."
    - winpty docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PAT" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY
