image: node:18-alpine

stages:
  - build_and_push

build_and_push:
  stage: build_and_push
  script:
    - apk add --no-cache git
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY_USER/react_ci_cd:latest .
    - docker login -u $CI_REGISTRY_USER -p $DOCKER_ACCESS_TOKEN
    - docker push $CI_REGISTRY_USER/react_ci_cd:latest
